######################################################################
# Automatically generated by qmake (2.00a) Mon Mar 20 12:40:56 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FilterButtonWidget.h \
           MainWindow.h \
           ResourceWidget.h \
           TabWidget.h \
           ../tab_files/task_tab_files/TaskTab.h \
           ../tab_files/task_tab_files/TaskFields.h \
           ../tab_files/task_tab_files/DependenciesFields.h \
           ../tab_files/task_tab_files/ResourcesFields.h \
           ../utility_classes_files/ExternalDataFields.h \
           ../utility_classes_files/BrowseWidget.h \
           ../tab_files/list_tab_files/ListTab.h \
           ../tab_files/gantt_tab_files/GanttTab.h \
           ../tab_files/pert_tab_files/PertTab.h \
           ../tab_files/resource_tab_files/ResourceTab.h \
           ../tab_files/milestone_tab_files/MilestoneTab.h \
           ../utility_classes_files/SearchWidget.h
SOURCES += FilterButtonWidget.cpp \
           MainWindow.cpp \
           ResourceWidget.cpp \
           TabWidget.cpp \
           ../tab_files/task_tab_files/TaskTab.cpp \
           ../tab_files/task_tab_files/TaskFields.cpp \
           ../tab_files/task_tab_files/DependenciesFields.cpp \
           ../tab_files/task_tab_files/ResourcesFields.cpp \
           ../utility_classes_files/ExternalDataFields.cpp \
           ../utility_classes_files/BrowseWidget.cpp \
           ../tab_files/list_tab_files/ListTab.cpp \
           ../tab_files/gantt_tab_files/GanttTab.cpp \
           ../tab_files/pert_tab_files/PertTab.cpp \
           ../tab_files/resource_tab_files/ResourceTab.cpp \
           ../tab_files/milestone_tab_files/MilestoneTab.cpp \
           ../utility_classes_files/SearchWidget.cpp
