######################################################################
# Automatically generated by qmake (2.00a) Tue Apr 11 22:56:27 2006
######################################################################

TEMPLATE = app
TARGET += 
RESOURCES += PMSPro.qrc
DEPENDPATH += . \
              data_classes_files \
              main_window_files \
	      main_window_files/side_widget_files \
              utility_classes_files \
              tab_files/milestone_tab_files \
              tab_files/resource_tab_files \
              tab_files/task_tab_files
INCLUDEPATH += . \
               main_window_files \
	       main_window_files/side_widget_files \
               data_classes_files \
               tab_files/task_tab_files \
               tab_files/resource_tab_files \
               tab_files/milestone_tab_files \
               utility_classes_files

# Input
HEADERS += glwidget.h \
           loginPrompt.h \
           data_classes_files/Resource.h \
           data_classes_files/Task.h \
	   data_classes_files/User.h \
	   data_classes_files/Kernel.h \
	   data_classes_files/Milestone.h \
	   data_classes_files/TaskManager.h \
	   data_classes_files/ResourceManager.h \
	   data_classes_files/MilestoneManager.h \
           main_window_files/MainWindow.h \
           main_window_files/ResourceWidget.h \
           main_window_files/TabWidget.h \
	   main_window_files/side_widget_files/SideWidget.h \
	   main_window_files/side_widget_files/MilestoneActionWidget.h \
	   main_window_files/side_widget_files/TaskActionWidget.h \
	   main_window_files/side_widget_files/ResourceActionWidget.h \
           utility_classes_files/BrowseWidget.h \
           utility_classes_files/ExternalDataFields.h \
           utility_classes_files/SearchWidget.h \
	   utility_classes_files/WorkLog.h \
           tab_files/milestone_tab_files/MilestoneTab.h \
           tab_files/resource_tab_files/ResourceTab.h \
           tab_files/task_tab_files/DependenciesFields.h \
           tab_files/task_tab_files/TaskFields.h \
           tab_files/task_tab_files/TaskTab.h
SOURCES += glwidget.cpp \
           main.cpp \
           loginPrompt.cpp \
           data_classes_files/Resource.cpp \
           data_classes_files/Task.cpp \
	   data_classes_files/User.cpp \
	   data_classes_files/Kernel.cpp \
	   data_classes_files/Milestone.cpp \
	   data_classes_files/TaskManager.cpp \
	   data_classes_files/ResourceManager.cpp \
	   data_classes_files/MilestoneManager.cpp \
           main_window_files/MainWindow.cpp \
           main_window_files/ResourceWidget.cpp \
           main_window_files/TabWidget.cpp \
	   main_window_files/side_widget_files/SideWidget.cpp \
	   main_window_files/side_widget_files/MilestoneActionWidget.cpp \
	   main_window_files/side_widget_files/TaskActionWidget.cpp \
	   main_window_files/side_widget_files/ResourceActionWidget.cpp \
           utility_classes_files/BrowseWidget.cpp \
           utility_classes_files/ExternalDataFields.cpp \
           utility_classes_files/SearchWidget.cpp \
	   utility_classes_files/WorkLog.cpp \
           tab_files/milestone_tab_files/MilestoneTab.cpp \
           tab_files/resource_tab_files/ResourceTab.cpp \
           tab_files/task_tab_files/DependenciesFields.cpp \
           tab_files/task_tab_files/TaskFields.cpp \
           tab_files/task_tab_files/TaskTab.cpp
QT += opengl
QT += sql
